apiVersion: pipecd.dev/v1beta1
kind: Application 
spec:
  name: PromptSafely
  plugins:
    opentofu:
      openTofuVersion: "1.10.5"
      workspace: default
      commandFlags: 
        plan:
        - "-no-color"
        # apply:
        # - "-auto-approve"

  pipeline:

  palnner: 