name: Push Docker Image

on:
  workflow_call:

jobs:
  push_image:
    runs-on:  ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Login to Registry
        run: echo "${{ secrets.REGISTRY_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build and Push
        run: |
          docker build -t ghcr.io/${{ github.repository }}:${{ github.sha }} .
          docker push ghcr.io/${{ github.repository }}:${{ github.sha }}
