name: Run Tests

on:
  workflow_call:

jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install uv (shared)
        uses: ./.github/actions/install-uv

      - name: Install dev dependencies
        run: uv pip install -r requirements-dev.txt --system

      - name: Run tests
        run: |
          uv run pytest --maxfail=1 --disable-warnings -q
